-- Source foreign key: B_AUDIT_EVENT_EVENT_TEMPLAT_FK
ALTER TABLE web50.B_AUDIT_EVENT
  ADD CONSTRAINT B_AUDIT_EVENT_EVENT_TEMPLAT_FK FOREIGN KEY (EVENT_ID)
    REFERENCES web50.B_AUDIT_EVENT_TEMPLATE(EVENT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_AUDIT_EVENT_USER_FK
ALTER TABLE web50.B_AUDIT_EVENT
  ADD CONSTRAINT B_AUDIT_EVENT_USER_FK FOREIGN KEY (USER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_AUDIT_EVENT_CATEGOR_MUSER_FK
/*ALTER TABLE web50.B_AUDIT_EVENT_CATEGORY
  ADD CONSTRAINT B_AUDIT_EVENT_CATEGOR_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_AUDIT_EVENT_CATEGOR_CUSER_FK
ALTER TABLE web50.B_AUDIT_EVENT_CATEGORY
  ADD CONSTRAINT B_AUDIT_EVENT_CATEGOR_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_AUDIT_EVENT_TEMPLAT_CUSER_FK
ALTER TABLE web50.B_AUDIT_EVENT_TEMPLATE
  ADD CONSTRAINT B_AUDIT_EVENT_TEMPLAT_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_AUDIT_EVENT_TEMPLAT_MUSER_FK
ALTER TABLE web50.B_AUDIT_EVENT_TEMPLATE
  ADD CONSTRAINT B_AUDIT_EVENT_TEMPLAT_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_AUDIT_EVENT_TEMPLAT_CATEG_FK
ALTER TABLE web50.B_AUDIT_EVENT_TEMPLATE
  ADD CONSTRAINT B_AUDIT_EVENT_TEMPLAT_CATEG_FK FOREIGN KEY (CATEGORY_ID)
    REFERENCES web50.B_AUDIT_EVENT_CATEGORY(CATEGORY_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_LOG_EVENT_SEVERITY_FK
ALTER TABLE web50.B_LOG_EVENT
  ADD CONSTRAINT B_LOG_EVENT_SEVERITY_FK FOREIGN KEY (SEVERITY)
    REFERENCES web50.B_LOG_SEVERITY_REF(SEVERITY)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_LOG_EVENT_USER_FK
ALTER TABLE web50.B_LOG_EVENT
  ADD CONSTRAINT B_LOG_EVENT_USER_FK FOREIGN KEY (USER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_LOG_EVENTS_CATEGORY_MUSER_FK
/*ALTER TABLE web50.B_LOG_EVENTS_CATEGORY
  ADD CONSTRAINT B_LOG_EVENTS_CATEGORY_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_LOG_EVENTS_CATEGORY_CUSER_FK
ALTER TABLE web50.B_LOG_EVENTS_CATEGORY
  ADD CONSTRAINT B_LOG_EVENTS_CATEGORY_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_LOG_SEVERITY_REF_CUSER_FK
ALTER TABLE web50.B_LOG_SEVERITY_REF
  ADD CONSTRAINT B_LOG_SEVERITY_REF_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_LOG_SEVERITY_REF_MUSER_FK
ALTER TABLE web50.B_LOG_SEVERITY_REF
  ADD CONSTRAINT B_LOG_SEVERITY_REF_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_POLICY_MUSER_FK
ALTER TABLE web50.B_POLICY
  ADD CONSTRAINT B_POLICY_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_POLICY_CUSER_FK
ALTER TABLE web50.B_POLICY
  ADD CONSTRAINT B_POLICY_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_POLICY_RULE_FILTERS_RULE_FK
ALTER TABLE web50.B_POLICY_RULE_FILTERS
  ADD CONSTRAINT B_POLICY_RULE_FILTERS_RULE_FK FOREIGN KEY (RULE_ID)
    REFERENCES web50.B_POLICY_RULES(RULE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_POLICY_RULE_MUSER_FK
/*ALTER TABLE web50.B_POLICY_RULE_FILTERS
  ADD CONSTRAINT B_POLICY_RULE_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_POLICY_RULE_CUSER_FK
ALTER TABLE web50.B_POLICY_RULE_FILTERS
  ADD CONSTRAINT B_POLICY_RULE_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_POLICY_RULES_POLICY_FK
ALTER TABLE web50.B_POLICY_RULES
  ADD CONSTRAINT B_POLICY_RULES_POLICY_FK FOREIGN KEY (POLICY_ID)
    REFERENCES web50.B_POLICY(POLICY_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_POLICY_RULES_CUSER_FK
/*ALTER TABLE web50.B_POLICY_RULES
  ADD CONSTRAINT B_POLICY_RULES_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_POLICY_RULES_MUSER_FK
ALTER TABLE web50.B_POLICY_RULES
  ADD CONSTRAINT B_POLICY_RULES_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_CUSER_FK
ALTER TABLE web50.B_ROLE
  ADD CONSTRAINT B_ROLE_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_ROLE_TO_B_POLICY_ROLE_FK
ALTER TABLE web50.B_ROLE_TO_B_POLICY
  ADD CONSTRAINT B_ROLE_TO_B_POLICY_ROLE_FK FOREIGN KEY (ROLE_ID)
    REFERENCES web50.B_ROLE(ROLE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_TO_B_POLICY_POLICY_FK
ALTER TABLE web50.B_ROLE_TO_B_POLICY
  ADD CONSTRAINT B_ROLE_TO_B_POLICY_POLICY_FK FOREIGN KEY (POLICY_ID)
    REFERENCES web50.B_POLICY(POLICY_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_TO_B_POLICY_MUSER_FK
/*ALTER TABLE web50.B_ROLE_TO_B_POLICY
  ADD CONSTRAINT B_ROLE_TO_B_POLICY_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_TO_B_POLICY_CUSER_FK
ALTER TABLE web50.B_ROLE_TO_B_POLICY
  ADD CONSTRAINT B_ROLE_TO_B_POLICY_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_ROLE_TO_B_ROLE_ROLE_FK
ALTER TABLE web50.B_ROLE_TO_B_ROLE
  ADD CONSTRAINT B_ROLE_TO_B_ROLE_ROLE_FK FOREIGN KEY (ROLE_ID)
    REFERENCES web50.B_ROLE(ROLE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_TO_B_ROLE_PAR_ROLE_FK
ALTER TABLE web50.B_ROLE_TO_B_ROLE
  ADD CONSTRAINT B_ROLE_TO_B_ROLE_PAR_ROLE_FK FOREIGN KEY (PARENT_ROLE_ID)
    REFERENCES web50.B_ROLE(ROLE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_TO_B_ROLE_MUSER_FK
/*ALTER TABLE web50.B_ROLE_TO_B_ROLE
  ADD CONSTRAINT B_ROLE_TO_B_ROLE_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_ROLE_TO_B_ROLE_CUSER_FK
ALTER TABLE web50.B_ROLE_TO_B_ROLE
  ADD CONSTRAINT B_ROLE_TO_B_ROLE_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_STATE_REF_MU_FK
ALTER TABLE web50.B_STATE_REF
  ADD CONSTRAINT B_STATE_REF_MU_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_STATE_REF_CU_FK
ALTER TABLE web50.B_STATE_REF
  ADD CONSTRAINT B_STATE_REF_CU_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_STATUS_REF_MUSER_FK
ALTER TABLE web50.B_STATUS_REF
  ADD CONSTRAINT B_STATUS_REF_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_STATUS_REF_CUSER_FK
ALTER TABLE web50.B_STATUS_REF
  ADD CONSTRAINT B_STATUS_REF_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_UNIT_REF_CUSER_FK
ALTER TABLE web50.B_UNIT_REF
  ADD CONSTRAINT B_UNIT_REF_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_UNIT_REF_MUSER_FK
ALTER TABLE web50.B_UNIT_REF
  ADD CONSTRAINT B_UNIT_REF_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_USER_AUTHMAPS_CUSER_FK
ALTER TABLE web50.B_USER_AUTHMAPS
  ADD CONSTRAINT B_USER_AUTHMAPS_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_USER_AUTHMAPS_MUSER_FK
ALTER TABLE web50.B_USER_AUTHMAPS
  ADD CONSTRAINT B_USER_AUTHMAPS_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_USER_AUTHMAPS_USER_FK
ALTER TABLE web50.B_USER_AUTHMAPS
  ADD CONSTRAINT B_USER_AUTHMAPS_USER_FK FOREIGN KEY (USER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_USER_PRIVATE_MUSER_FK
/*ALTER TABLE web50.B_USER_PRIVATE
  ADD CONSTRAINT B_USER_PRIVATE_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: B_USER_PRIVATE_USER_FK
ALTER TABLE web50.B_USER_PRIVATE
  ADD CONSTRAINT B_USER_PRIVATE_USER_FK FOREIGN KEY (USER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
    /*
-- Source foreign key: B_USER_PRIVATE_CUSER_FK
ALTER TABLE web50.B_USER_PRIVATE
  ADD CONSTRAINT B_USER_PRIVATE_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_USER_PUBLIC_CUSER_FK
ALTER TABLE web50.B_USER_PUBLIC
  ADD CONSTRAINT B_USER_PUBLIC_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_USER_PUBLIC_MUSER_FK
ALTER TABLE web50.B_USER_PUBLIC
  ADD CONSTRAINT B_USER_PUBLIC_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
      */
-- Source foreign key: B_USER_TO_B_ROLE_USER_FK
ALTER TABLE web50.B_USER_TO_B_ROLE
  ADD CONSTRAINT B_USER_TO_B_ROLE_USER_FK FOREIGN KEY (USER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
        /*
-- Source foreign key: B_USER_TO_B_ROLE_MUSER_FK
ALTER TABLE web50.B_USER_TO_B_ROLE
  ADD CONSTRAINT B_USER_TO_B_ROLE_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
          */
-- Source foreign key: B_USER_TO_B_ROLE_ROLE_FK
ALTER TABLE web50.B_USER_TO_B_ROLE
  ADD CONSTRAINT B_USER_TO_B_ROLE_ROLE_FK FOREIGN KEY (ROLE_ID)
    REFERENCES web50.B_ROLE(ROLE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: B_USER_TO_B_ROLE_CUSER_FK
/*ALTER TABLE web50.B_USER_TO_B_ROLE
  ADD CONSTRAINT B_USER_TO_B_ROLE_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_GEOM_MUSER_FK
ALTER TABLE web50.LIB_COVERAGE
  ADD CONSTRAINT LIB_DOC_GEOM_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_GEOM_CUSER_FK
ALTER TABLE web50.LIB_COVERAGE
  ADD CONSTRAINT LIB_DOC_GEOM_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: LIB_DOC_B_STATUS_FK
ALTER TABLE web50.LIB_DOC
  ADD CONSTRAINT LIB_DOC_B_STATUS_FK FOREIGN KEY (STATUS_ID)
    REFERENCES web50.B_STATUS_REF(STATUS_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_MUSER_FK
/*ALTER TABLE web50.LIB_DOC
  ADD CONSTRAINT LIB_DOC_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_CUSER_FK
ALTER TABLE web50.LIB_DOC
  ADD CONSTRAINT LIB_DOC_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: LIB_DOC_LIB_DOC_FK
ALTER TABLE web50.LIB_DOC
  ADD CONSTRAINT LIB_DOC_LIB_DOC_FK FOREIGN KEY (PARENT_DOC_ID)
    REFERENCES web50.LIB_DOC(DOC_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_GEOMETRY_FK
ALTER TABLE web50.LIB_DOC
  ADD CONSTRAINT LIB_DOC_GEOMETRY_FK FOREIGN KEY (GID)
    REFERENCES web50.LIB_COVERAGE(GID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_LIB_DOC_TYPE_FK
ALTER TABLE web50.LIB_DOC
  ADD CONSTRAINT LIB_DOC_LIB_DOC_TYPE_FK FOREIGN KEY (DOC_TYPE_ID)
    REFERENCES web50.LIB_DOC_TYPE_REF(DOC_TYPE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_A_MUSER_FK
/*ALTER TABLE web50.LIB_DOC_A
  ADD CONSTRAINT LIB_DOC_A_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_A_CUSER_FK
ALTER TABLE web50.LIB_DOC_A
  ADD CONSTRAINT LIB_DOC_A_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_TYPE_REF_MUSER_FK
ALTER TABLE web50.LIB_DOC_TYPE_REF
  ADD CONSTRAINT LIB_DOC_TYPE_REF_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_TYPE_REF_CUSER_FK
ALTER TABLE web50.LIB_DOC_TYPE_REF
  ADD CONSTRAINT LIB_DOC_TYPE_REF_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_VERSION_MUSER_FK
ALTER TABLE web50.LIB_DOC_VERSION
  ADD CONSTRAINT LIB_DOC_VERSION_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_VERSION_CUSER_FK
ALTER TABLE web50.LIB_DOC_VERSION
  ADD CONSTRAINT LIB_DOC_VERSION_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: LIB_DOC_VERSION_STORAGE_FK
ALTER TABLE web50.LIB_DOC_VERSION
  ADD CONSTRAINT LIB_DOC_VERSION_STORAGE_FK FOREIGN KEY (STORAGE_ID)
    REFERENCES web50.LIB_STORAGE(STORAGE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_VER_MIME_TYPE_FK
ALTER TABLE web50.LIB_DOC_VERSION
  ADD CONSTRAINT LIB_DOC_VER_MIME_TYPE_FK FOREIGN KEY (MIME_TYPE_ID)
    REFERENCES web50.LIB_MIME_TYPE_REF(MIME_TYPE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_VERSION_SELF_FK
ALTER TABLE web50.LIB_DOC_VERSION
  ADD CONSTRAINT LIB_DOC_VERSION_SELF_FK FOREIGN KEY (NEXT_DOC_VERSION_ID)
    REFERENCES web50.LIB_DOC_VERSION(DOC_VERSION_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_DOC_VERSION_LIB_DOC_FK
ALTER TABLE web50.LIB_DOC_VERSION
  ADD CONSTRAINT LIB_DOC_VERSION_LIB_DOC_FK FOREIGN KEY (DOC_ID)
    REFERENCES web50.LIB_DOC(DOC_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_MIME_TYPE_REF_MUSER_FK
/*ALTER TABLE web50.LIB_MIME_TYPE_REF
  ADD CONSTRAINT LIB_MIME_TYPE_REF_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_MIME_TYPE_REF_CUSER_FK
ALTER TABLE web50.LIB_MIME_TYPE_REF
  ADD CONSTRAINT LIB_MIME_TYPE_REF_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: LIB_STORAGE_CUSER_FK
ALTER TABLE web50.LIB_STORAGE
  ADD CONSTRAINT LIB_STORAGE_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: LNK_GATE_FOR_LNK_LINK_TYPE_REF
ALTER TABLE web50.LNK_GATE
  ADD CONSTRAINT LNK_GATE_FOR_LNK_LINK_TYPE_REF FOREIGN KEY (LNK_TYPE_ID)
    REFERENCES web50.LNK_LINK_TYPE_REF(LNK_TYPE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_GIDR_LP_ZONE_FK
ALTER TABLE web50.M_1_GIDR_LP
  ADD CONSTRAINT M_1_GIDR_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_GIDR_S_ZONE_FK
ALTER TABLE web50.M_1_GIDR_S
  ADD CONSTRAINT M_1_GIDR_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_GRUNT_ZONE_FK
ALTER TABLE web50.M_1_GRUNT
  ADD CONSTRAINT M_1_GRUNT_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_LIMITS_ZONE_FK
ALTER TABLE web50.M_1_LIMITS
  ADD CONSTRAINT M_1_LIMITS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_PROM_GAS_ZONE_FK
ALTER TABLE web50.M_1_PROM_GAS
  ADD CONSTRAINT M_1_PROM_GAS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_PROM_LP_ZONE_FK
ALTER TABLE web50.M_1_PROM_LP
  ADD CONSTRAINT M_1_PROM_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_PROM_S_ZONE_FK
ALTER TABLE web50.M_1_PROM_S
  ADD CONSTRAINT M_1_PROM_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_RAST_LP_ZONE_FK
ALTER TABLE web50.M_1_RAST_LP
  ADD CONSTRAINT M_1_RAST_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_RAST_S_ZONE_FK
ALTER TABLE web50.M_1_RAST_S
  ADD CONSTRAINT M_1_RAST_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_RELIEF_ZONE_FK
ALTER TABLE web50.M_1_RELIEF
  ADD CONSTRAINT M_1_RELIEF_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_ROADS_LP_ZONE_FK
ALTER TABLE web50.M_1_ROADS_LP
  ADD CONSTRAINT M_1_ROADS_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_ROADS_S_ZONE_FK
ALTER TABLE web50.M_1_ROADS_S
  ADD CONSTRAINT M_1_ROADS_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_SURVEY_ZONE_FK
ALTER TABLE web50.M_1_SURVEY
  ADD CONSTRAINT M_1_SURVEY_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_SWAMP_ZONE_FK
ALTER TABLE web50.M_1_SWAMP
  ADD CONSTRAINT M_1_SWAMP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_TEXT_ZONE_FK
ALTER TABLE web50.M_1_TEXT
  ADD CONSTRAINT M_1_TEXT_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_TOWN_LP_ZONE_FK
ALTER TABLE web50.M_1_TOWN_LP
  ADD CONSTRAINT M_1_TOWN_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_TOWN_S_ZONE_FK
ALTER TABLE web50.M_1_TOWN_S
  ADD CONSTRAINT M_1_TOWN_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_ZONE_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_1_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_1_ZONE_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1_ZONE_TO_SRV_D_ZONE_FK
ALTER TABLE web50.M_1_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_1_ZONE_TO_SRV_D_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_1_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_GIDR_LP_ZONE_FK
ALTER TABLE web50.M_10_GIDR_LP
  ADD CONSTRAINT M_10_GIDR_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_GIDR_S_ZONE_FK
ALTER TABLE web50.M_10_GIDR_S
  ADD CONSTRAINT M_10_GIDR_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_LIMITS_ZONE_FK
ALTER TABLE web50.M_10_LIMITS
  ADD CONSTRAINT M_10_LIMITS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_PROM_GAS_ZONE_FK
ALTER TABLE web50.M_10_PROM_GAS
  ADD CONSTRAINT M_10_PROM_GAS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_PROM_LP_ZONE_FK
ALTER TABLE web50.M_10_PROM_LP
  ADD CONSTRAINT M_10_PROM_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_PROM_S_ZONE_FK
ALTER TABLE web50.M_10_PROM_S
  ADD CONSTRAINT M_10_PROM_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_RAST_LP_ZONE_FK
ALTER TABLE web50.M_10_RAST_LP
  ADD CONSTRAINT M_10_RAST_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_RAST_S_ZONE_FK
ALTER TABLE web50.M_10_RAST_S
  ADD CONSTRAINT M_10_RAST_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_RELIEF_ZONE_FK
ALTER TABLE web50.M_10_RELIEF
  ADD CONSTRAINT M_10_RELIEF_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_ROADS_LP_ZONE_FK
ALTER TABLE web50.M_10_ROADS_LP
  ADD CONSTRAINT M_10_ROADS_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_ROADS_S_ZONE_FK
ALTER TABLE web50.M_10_ROADS_S
  ADD CONSTRAINT M_10_ROADS_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_SURVEY_ZONE_FK
ALTER TABLE web50.M_10_SURVEY
  ADD CONSTRAINT M_10_SURVEY_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_SWAMP_ZONE_FK
ALTER TABLE web50.M_10_SWAMP
  ADD CONSTRAINT M_10_SWAMP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_TEXT_ZONE_FK
ALTER TABLE web50.M_10_TEXT
  ADD CONSTRAINT M_10_TEXT_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_TOWN_LP_ZONE_FK
ALTER TABLE web50.M_10_TOWN_LP
  ADD CONSTRAINT M_10_TOWN_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_TOWN_S_ZONE_FK
ALTER TABLE web50.M_10_TOWN_S
  ADD CONSTRAINT M_10_TOWN_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_ZONE_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_10_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_10_ZONE_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_10_ZONE_TO_SRV_D_ZONE_FK
ALTER TABLE web50.M_10_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_10_ZONE_TO_SRV_D_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_10_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_GIDR_LP_NOM_FK
ALTER TABLE web50.M_100_GIDR_LP
  ADD CONSTRAINT M_100_GIDR_LP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_GIDR_S_NOM_FK
ALTER TABLE web50.M_100_GIDR_S
  ADD CONSTRAINT M_100_GIDR_S_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_LIMITS_NOM_FK
ALTER TABLE web50.M_100_LIMITS
  ADD CONSTRAINT M_100_LIMITS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_NOM_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_100_NOM_TO_SRV_DISTRICT
  ADD CONSTRAINT M_100_NOM_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_NOM_TO_SRV_D_NOM_FK
ALTER TABLE web50.M_100_NOM_TO_SRV_DISTRICT
  ADD CONSTRAINT M_100_NOM_TO_SRV_D_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_PROM_NOM_FK
ALTER TABLE web50.M_100_PROM
  ADD CONSTRAINT M_100_PROM_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_PROM_GAS_NOM_FK
ALTER TABLE web50.M_100_PROM_GAS
  ADD CONSTRAINT M_100_PROM_GAS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_RAST_LP_NOM_FK
ALTER TABLE web50.M_100_RAST_LP
  ADD CONSTRAINT M_100_RAST_LP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_RAST_S_NOM_FK
ALTER TABLE web50.M_100_RAST_S
  ADD CONSTRAINT M_100_RAST_S_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_RELIEF_NOM_FK
ALTER TABLE web50.M_100_RELIEF
  ADD CONSTRAINT M_100_RELIEF_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_ROADS_NOM_FK
ALTER TABLE web50.M_100_ROADS
  ADD CONSTRAINT M_100_ROADS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_SURVEY_NOM_FK
ALTER TABLE web50.M_100_SURVEY
  ADD CONSTRAINT M_100_SURVEY_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_SWAMP_NOM_FK
ALTER TABLE web50.M_100_SWAMP
  ADD CONSTRAINT M_100_SWAMP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_TEXT_NOM_FK
ALTER TABLE web50.M_100_TEXT
  ADD CONSTRAINT M_100_TEXT_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_100_TOWN_NOM_FK
ALTER TABLE web50.M_100_TOWN
  ADD CONSTRAINT M_100_TOWN_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_100_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_GIDR_LP_NOM_FK
ALTER TABLE web50.M_1K_GIDR_LP
  ADD CONSTRAINT M_1K_GIDR_LP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_GIDR_S_NOM_FK
ALTER TABLE web50.M_1K_GIDR_S
  ADD CONSTRAINT M_1K_GIDR_S_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_LIMITS_NOM_FK
ALTER TABLE web50.M_1K_LIMITS
  ADD CONSTRAINT M_1K_LIMITS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_NOM_TO_SRV_D_NOM_FK
ALTER TABLE web50.M_1K_NOM_TO_SRV_DISTRICT
  ADD CONSTRAINT M_1K_NOM_TO_SRV_D_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_NOM_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_1K_NOM_TO_SRV_DISTRICT
  ADD CONSTRAINT M_1K_NOM_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_PROM_NOM_FK
ALTER TABLE web50.M_1K_PROM
  ADD CONSTRAINT M_1K_PROM_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_PROM_GAS_NOM_FK
ALTER TABLE web50.M_1K_PROM_GAS
  ADD CONSTRAINT M_1K_PROM_GAS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_RAST_LP_NOM_FK
ALTER TABLE web50.M_1K_RAST_LP
  ADD CONSTRAINT M_1K_RAST_LP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_RAST_S_NOM_FK
ALTER TABLE web50.M_1K_RAST_S
  ADD CONSTRAINT M_1K_RAST_S_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_RELIEF_NOM_FK
ALTER TABLE web50.M_1K_RELIEF
  ADD CONSTRAINT M_1K_RELIEF_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_ROADS_NOM_FK
ALTER TABLE web50.M_1K_ROADS
  ADD CONSTRAINT M_1K_ROADS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_SURVEY_NOM_FK
ALTER TABLE web50.M_1K_SURVEY
  ADD CONSTRAINT M_1K_SURVEY_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_SWAMP_NOM_FK
ALTER TABLE web50.M_1K_SWAMP
  ADD CONSTRAINT M_1K_SWAMP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_TEXT_NOM_FK
ALTER TABLE web50.M_1K_TEXT
  ADD CONSTRAINT M_1K_TEXT_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_1K_TOWN_NOM_FK
ALTER TABLE web50.M_1K_TOWN
  ADD CONSTRAINT M_1K_TOWN_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_1K_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_GIDR_LP_NOM_FK
ALTER TABLE web50.M_200_GIDR_LP
  ADD CONSTRAINT M_200_GIDR_LP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_GIDR_S_NOM_FK
ALTER TABLE web50.M_200_GIDR_S
  ADD CONSTRAINT M_200_GIDR_S_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_LIMITS_NOM_FK
ALTER TABLE web50.M_200_LIMITS
  ADD CONSTRAINT M_200_LIMITS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_NOM_TO_SRV_D_NOM_FK
ALTER TABLE web50.M_200_NOM_TO_SRV_DISTRICT
  ADD CONSTRAINT M_200_NOM_TO_SRV_D_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_NOM_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_200_NOM_TO_SRV_DISTRICT
  ADD CONSTRAINT M_200_NOM_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_PROM_NOM_FK
ALTER TABLE web50.M_200_PROM
  ADD CONSTRAINT M_200_PROM_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_PROM_GAS_NOM_FK
ALTER TABLE web50.M_200_PROM_GAS
  ADD CONSTRAINT M_200_PROM_GAS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_RAST_LP_NOM_FK
ALTER TABLE web50.M_200_RAST_LP
  ADD CONSTRAINT M_200_RAST_LP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_RAST_S_NOM_FK
ALTER TABLE web50.M_200_RAST_S
  ADD CONSTRAINT M_200_RAST_S_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_RELIEF_NOM_FK
ALTER TABLE web50.M_200_RELIEF
  ADD CONSTRAINT M_200_RELIEF_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_ROADS_NOM_FK
ALTER TABLE web50.M_200_ROADS
  ADD CONSTRAINT M_200_ROADS_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_SURVEY_NOM_FK
ALTER TABLE web50.M_200_SURVEY
  ADD CONSTRAINT M_200_SURVEY_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_SWAMP_NOM_FK
ALTER TABLE web50.M_200_SWAMP
  ADD CONSTRAINT M_200_SWAMP_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_TEXT_NOM_FK
ALTER TABLE web50.M_200_TEXT
  ADD CONSTRAINT M_200_TEXT_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_200_TOWN_NOM_FK
ALTER TABLE web50.M_200_TOWN
  ADD CONSTRAINT M_200_TOWN_NOM_FK FOREIGN KEY (NOMENCLATURE)
    REFERENCES web50.M_200_NOMENCLATURE_REF(NOMENCLATURE)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_GIDR_LP_ZONE_FK
ALTER TABLE web50.M_25_GIDR_LP
  ADD CONSTRAINT M_25_GIDR_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_GIDR_S_ZONE_FK
ALTER TABLE web50.M_25_GIDR_S
  ADD CONSTRAINT M_25_GIDR_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_LIMITS_ZONE_FK
ALTER TABLE web50.M_25_LIMITS
  ADD CONSTRAINT M_25_LIMITS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_PROM_GAS_ZONE_FK
ALTER TABLE web50.M_25_PROM_GAS
  ADD CONSTRAINT M_25_PROM_GAS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_PROM_LP_ZONE_FK
ALTER TABLE web50.M_25_PROM_LP
  ADD CONSTRAINT M_25_PROM_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_PROM_S_ZONE_FK
ALTER TABLE web50.M_25_PROM_S
  ADD CONSTRAINT M_25_PROM_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_RAST_LP_ZONE_FK
ALTER TABLE web50.M_25_RAST_LP
  ADD CONSTRAINT M_25_RAST_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_RAST_S_ZONE_FK
ALTER TABLE web50.M_25_RAST_S
  ADD CONSTRAINT M_25_RAST_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_RELIEF_ZONE_FK
ALTER TABLE web50.M_25_RELIEF
  ADD CONSTRAINT M_25_RELIEF_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_ROADS_LP_ZONE_FK
ALTER TABLE web50.M_25_ROADS_LP
  ADD CONSTRAINT M_25_ROADS_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_ROADS_S_ZONE_FK
ALTER TABLE web50.M_25_ROADS_S
  ADD CONSTRAINT M_25_ROADS_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_SURVEY_ZONE_FK
ALTER TABLE web50.M_25_SURVEY
  ADD CONSTRAINT M_25_SURVEY_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_SWAMP_ZONE_FK
ALTER TABLE web50.M_25_SWAMP
  ADD CONSTRAINT M_25_SWAMP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_TEXT_ZONE_FK
ALTER TABLE web50.M_25_TEXT
  ADD CONSTRAINT M_25_TEXT_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_TOWN_LP_ZONE_FK
ALTER TABLE web50.M_25_TOWN_LP
  ADD CONSTRAINT M_25_TOWN_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_TOWN_S_ZONE_FK
ALTER TABLE web50.M_25_TOWN_S
  ADD CONSTRAINT M_25_TOWN_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_ZONE_TO_SRV_D_ZONE_FK
ALTER TABLE web50.M_25_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_25_ZONE_TO_SRV_D_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_25_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_25_ZONE_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_25_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_25_ZONE_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_GIDR_LP_ZONE_FK
ALTER TABLE web50.M_5_GIDR_LP
  ADD CONSTRAINT M_5_GIDR_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_GIDR_S_ZONE_FK
ALTER TABLE web50.M_5_GIDR_S
  ADD CONSTRAINT M_5_GIDR_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_GRUNT_ZONE_FK
ALTER TABLE web50.M_5_GRUNT
  ADD CONSTRAINT M_5_GRUNT_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_LIMITS_ZONE_FK
ALTER TABLE web50.M_5_LIMITS
  ADD CONSTRAINT M_5_LIMITS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_PROM_GAS_ZONE_FK
ALTER TABLE web50.M_5_PROM_GAS
  ADD CONSTRAINT M_5_PROM_GAS_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_PROM_LP_ZONE_FK
ALTER TABLE web50.M_5_PROM_LP
  ADD CONSTRAINT M_5_PROM_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_PROM_S_ZONE_FK
ALTER TABLE web50.M_5_PROM_S
  ADD CONSTRAINT M_5_PROM_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_RAST_LP_ZONE_FK
ALTER TABLE web50.M_5_RAST_LP
  ADD CONSTRAINT M_5_RAST_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_RAST_S_ZONE_FK
ALTER TABLE web50.M_5_RAST_S
  ADD CONSTRAINT M_5_RAST_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_RELIEF_ZONE_FK
ALTER TABLE web50.M_5_RELIEF
  ADD CONSTRAINT M_5_RELIEF_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_ROADS_LP_ZONE_FK
ALTER TABLE web50.M_5_ROADS_LP
  ADD CONSTRAINT M_5_ROADS_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_ROADS_S_ZONE_FK
ALTER TABLE web50.M_5_ROADS_S
  ADD CONSTRAINT M_5_ROADS_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_SURVEY_ZONE_FK
ALTER TABLE web50.M_5_SURVEY
  ADD CONSTRAINT M_5_SURVEY_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_SWAMP_ZONE_FK
ALTER TABLE web50.M_5_SWAMP
  ADD CONSTRAINT M_5_SWAMP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_TEXT_ZONE_FK
ALTER TABLE web50.M_5_TEXT
  ADD CONSTRAINT M_5_TEXT_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_TOWN_LP_ZONE_FK
ALTER TABLE web50.M_5_TOWN_LP
  ADD CONSTRAINT M_5_TOWN_LP_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_TOWN_S_ZONE_FK
ALTER TABLE web50.M_5_TOWN_S
  ADD CONSTRAINT M_5_TOWN_S_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_ZONE_TO_SRV_D_ZONE_FK
ALTER TABLE web50.M_5_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_5_ZONE_TO_SRV_D_ZONE_FK FOREIGN KEY (ZONE_ID)
    REFERENCES web50.M_5_ZONE(ZONE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_5_ZONE_TO_SRV_D_SRV_FK
ALTER TABLE web50.M_5_ZONE_TO_SRV_DISTRICT
  ADD CONSTRAINT M_5_ZONE_TO_SRV_D_SRV_FK FOREIGN KEY (SRV_DISTRICT_ID)
    REFERENCES pods.SRV_DISTRICT_GCL(SRV_DISTRICT_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_OBJ_CLS_GR_CLASS_FK
ALTER TABLE web50.M_OBJ_CLS_GROUP_REF
  ADD CONSTRAINT M_OBJ_CLS_GR_CLASS_FK FOREIGN KEY (CLASSIFIER_ID)
    REFERENCES web50.M_CLASSIFIER_REF(CLASSIFIER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_OBJ_CLS_CLASS_FK
ALTER TABLE web50.M_OBJ_CLS_REF
  ADD CONSTRAINT M_OBJ_CLS_CLASS_FK FOREIGN KEY (CLASSIFIER_ID)
    REFERENCES web50.M_CLASSIFIER_REF(CLASSIFIER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_OBJ_CLS_OBJ_GROUP_FK
ALTER TABLE web50.M_OBJ_CLS_REF
  ADD CONSTRAINT M_OBJ_CLS_OBJ_GROUP_FK FOREIGN KEY (OBJ_CLS_GROUP_ID,CLASSIFIER_ID)
    REFERENCES web50.M_OBJ_CLS_GROUP_REF(OBJ_CLS_GROUP_ID,CLASSIFIER_ID)
--    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: M_OBJ_CLS_TOPO_FK
ALTER TABLE web50.M_OBJ_CLS_REF
  ADD CONSTRAINT M_OBJ_CLS_TOPO_FK FOREIGN KEY (TOPOLOGY_ID)
    REFERENCES web50.M_TOPOLOGY_REF(TOPOLOGY_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: POI_COORD_FOR_POI_COORD_TYPE
ALTER TABLE web50.POI_COORD
  ADD CONSTRAINT POI_COORD_FOR_POI_COORD_TYPE FOREIGN KEY (COORD_TYPE_ID)
    REFERENCES web50.POI_COORD_TYPE_REF(COORD_TYPE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: POI_POINT_FOR_POI_COORD
ALTER TABLE web50.POI_POINT
  ADD CONSTRAINT POI_POINT_FOR_POI_COORD FOREIGN KEY (COORD_ID)
    REFERENCES web50.POI_COORD(COORD_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: POI_POINT_FOR_B_STATUS
ALTER TABLE web50.POI_POINT
  ADD CONSTRAINT POI_POINT_FOR_B_STATUS FOREIGN KEY (STATUS_ID)
    REFERENCES web50.B_STATUS_REF(STATUS_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: POI_TRACK_FOR_B_STATUS
ALTER TABLE web50.POI_TRACK
  ADD CONSTRAINT POI_TRACK_FOR_B_STATUS FOREIGN KEY (STATUS_ID)
    REFERENCES web50.B_STATUS_REF(STATUS_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: POI_TRACK_FOR_TO_POI_COORD
ALTER TABLE web50.POI_TRACK_TO_POI_COORD
  ADD CONSTRAINT POI_TRACK_FOR_TO_POI_COORD FOREIGN KEY (COORD_ID)
    REFERENCES web50.POI_COORD(COORD_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: POI_TRACK_TO_FOR_POI_COORD
ALTER TABLE web50.POI_TRACK_TO_POI_COORD
  ADD CONSTRAINT POI_TRACK_TO_FOR_POI_COORD FOREIGN KEY (TRACK_ID)
    REFERENCES web50.POI_TRACK(TRACK_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_INDEX_OBJ_CU_FK
/*ALTER TABLE web50.PS_INDEX_OBJ
  ADD CONSTRAINT PS_INDEX_OBJ_CU_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_INDEX_OBJ_MU_FK
ALTER TABLE web50.PS_INDEX_OBJ
  ADD CONSTRAINT PS_INDEX_OBJ_MU_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: PS_INDEX_OBJ_STATE_FK
ALTER TABLE web50.PS_INDEX_OBJ
  ADD CONSTRAINT PS_INDEX_OBJ_STATE_FK FOREIGN KEY (STATE_ID)
    REFERENCES web50.B_STATE_REF(STATE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_INDEX_OBJ_GID_FK
ALTER TABLE web50.PS_INDEX_OBJ
  ADD CONSTRAINT PS_INDEX_OBJ_GID_FK FOREIGN KEY (GID)
    REFERENCES web50.PS_INDEX_OBJ_G(GID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_INDEX_OBJ_TEMP_PS_FK
ALTER TABLE web50.PS_INDEX_OBJ
  ADD CONSTRAINT PS_INDEX_OBJ_TEMP_PS_FK FOREIGN KEY (TEMPLATE_ID)
    REFERENCES web50.PS_INDEX_OBJ_TEMPLATE(TEMPLATE_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_IND_OBJ_TEMP_CU_FK
/*ALTER TABLE web50.PS_INDEX_OBJ_TEMPLATE
  ADD CONSTRAINT PS_IND_OBJ_TEMP_CU_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_IND_OBJ_TEMP_MU_FK
ALTER TABLE web50.PS_INDEX_OBJ_TEMPLATE
  ADD CONSTRAINT PS_IND_OBJ_TEMP_MU_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: PS_IND_OBJ_TEMP_MAP_FK
ALTER TABLE web50.PS_INDEX_OBJ_TEMPLATE
  ADD CONSTRAINT PS_IND_OBJ_TEMP_MAP_FK FOREIGN KEY (MAP_ID)
    REFERENCES web50.M_MAP(MAP_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: PS_INDEX_OBJ_TEMPLATE_PS_FK
ALTER TABLE web50.PS_INDEX_OBJ_TEMPLATE
  ADD CONSTRAINT PS_INDEX_OBJ_TEMPLATE_PS_FK FOREIGN KEY (PIPE_SYSTEM_ID)
    REFERENCES pods.PIPE_SYSTEM_CL(PIPE_SYSTEM_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: WKB_GC_MUSER_FK
/*ALTER TABLE web50.WKB_GEOMETRY_COLUMNS
  ADD CONSTRAINT WKB_GC_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: WKB_GC_CUSER_FK
ALTER TABLE web50.WKB_GEOMETRY_COLUMNS
  ADD CONSTRAINT WKB_GC_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */
-- Source foreign key: WKB_GC_SRID_FK
ALTER TABLE web50.WKB_GEOMETRY_COLUMNS
  ADD CONSTRAINT WKB_GC_SRID_FK FOREIGN KEY (SRID)
    REFERENCES web50.WKB_SPATIAL_REF_SYS(SRID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: SRS_CUSER_FK
/*ALTER TABLE web50.WKB_SPATIAL_REF_SYS
  ADD CONSTRAINT SRS_CUSER_FK FOREIGN KEY (CUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;

-- Source foreign key: SRS_MUSER_FK
ALTER TABLE web50.WKB_SPATIAL_REF_SYS
  ADD CONSTRAINT SRS_MUSER_FK FOREIGN KEY (MUSER_ID)
    REFERENCES web50.B_USER_PUBLIC(USER_ID)
    MATCH FULL
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE;
  */